config/routes.rb
Library::Application.routes.draw do
  devise_for :users
 
 resources :reservations

 resources :books do
  #get 'page/:page', :action => :index, :on => :collection
  	collection do
  		get 'search'
  	end
  end

  	
  
post "/books/search" => "books#search_results", as: 'search'
#get "/books" => "books#index", as: 'books'
#get "/books/new" => "books#new", as: 'new_book'
#get "/books/:id" => "books#show", as: 'book'
#post "/books" => "books#create"
#get "/books/:id/edit" => "books#edit", as: 'edit_book'
#patch "/books/:id" => "books#update"
#delete "/books/:id" => "books#destroy"


get "/users/sign_up", as: 'users_sign'

get "/users" => "users#index", as: 'users'
get "/users/:id" => "users#show", as: 'user'
get "/users/:id/edit" => "users#edit", as: 'edit_user'
patch "/users/:id" => "users#update"
delete "/users/:id" => "users#destroy"

#get "/reservations" => "reservations#index", as: 'reservations'
#get "/reservations/new" => "reservations#new", as: 'new_reservation'
#get "/reservations/:id" => "reservations#show", as: 'reservation'
#post "/reservations" => "reservations#create"
#get "/reservations/:id/edit" => "reservations#edit", as: 'edit_reservation'
#patch "/reservations/:id" => "reservations#update"
#delete "/reservations/:id" => "reservations#destroy"

get "/overdue" => "reservations#overdue", as: 'overdue'




resources :authors

root 'books#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

	def index
		@available_at = Time.now
		@authors = Author.order(:name)
	end

	def new
		@author = Author.new
	end
	
	def show
		@author = Author.find(params[:id])
    	@books = Book.where('author_id' => params[:id])
	end


	def create
		@author = Author.new(author_params)
		if @author.save
			redirect_to @author, notice: "#{@author.name} was created!"
		else
			render :new
		end
	end

	def edit
	end

	def update
		if @author.update(author_params)
			redirect_to @author, notice: "#{@author.name} was upadated!"
		else
			render :new
		end
	end

	def destroy
		@author.destroy
		redirect_to authors_url
	end

	private

	def author_params
		params.require(:author).permit(:name)
	end

	before_action :set_author, only: [ :show, :edit, :update, :destroy]

	def set_author
		@author = Author.find(params[:id])
	end

end

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <%= render 'shared/validation_errors', object: @author %>
  <%= f.label :name %> <%= f.text_field :name, autofocus: true %><br />
  <%= f.label :dob %> <%= f.text_field :dob %><br />
  <%= f.label :nationality %> <%= f.text_field :nationality %><br />
  <%= f.label :awards %> <%= f.text_field :awards %><br />
  <%= f.label :biography %> <%= f.text_field :biography %><br />
  <%= f.label :image_url %> <%= f.text_field :image_url %><br />
  <p>
    <%= f.submit %>
    <%= link_to 'Cancel', authors_path %>
  </p>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing <%= @author.name %></h1>
<%= render 'form' %>

app/views/authors/index.html.erb
Welcome <%= current_user.username %>

<p>Available as of <%= formatted_time(@available_at) %></p>
<ul>
	<% @authors.each do |author| %>
  <li>
  		<%= link_to(author.name, author) %>
	</li>
<% end %>
</ul>

app/views/authors/new.html.erb
<h1>Create a New Author</h1>
<%= render 'form' %>

app/views/authors/show.html.erb
<% content_for :name, @author.name %>
<article class="author">
  <header>
  </header>
  <p><label>Name:</label> <%= link_to(@author.name, @author) %></p>
  <p><%= image_tag("trophy.gif", :alt => "rach") %></p>
  <p><label>DOB:</label> <%= @author.dob %></p>
  <p><label>Nationality:</label> <%= @author.nationality %></p>
  <p><label>Awards:</label> <%= @author.awards %></p>
  <p><label>Biography:</label> <%= @author.biography %></p>  
  
</article>

<%= link_to 'All Authors', authors_path %> <%- if current_user.try(:admin?)%>| <%= link_to 'Edit', edit_author_path(@author) %>
<% if(@books.present?) %>

  <ul>
    <% @books.each do |book| %>
    <li>
        <%= link_to(book.title, book) %>
        by <%= link_to(book.author.name, book.author) %><br/>
   </li>
  <% end %>
<% end %>

<% if(!@books.present?) %>

<%= button_to 'Delete', @author,
				method: :delete,
				data: { confirm: 'Are you sure?' } %>
        <% end %> 
<% end %>