config/routes.rb
Library::Application.routes.draw do
  devise_for :users
 
 resources :reservations

 resources :books do
  #get 'page/:page', :action => :index, :on => :collection
  	collection do
  		get 'search'
  	end
  end

  	
  
post "/books/search" => "books#search_results", as: 'search'
#get "/books" => "books#index", as: 'books'
#get "/books/new" => "books#new", as: 'new_book'
#get "/books/:id" => "books#show", as: 'book'
#post "/books" => "books#create"
#get "/books/:id/edit" => "books#edit", as: 'edit_book'
#patch "/books/:id" => "books#update"
#delete "/books/:id" => "books#destroy"


get "/users/sign_up", as: 'users_sign'

get "/users" => "users#index", as: 'users'
get "/users/:id" => "users#show", as: 'user'
get "/users/:id/edit" => "users#edit", as: 'edit_user'
patch "/users/:id" => "users#update"
delete "/users/:id" => "users#destroy"

#get "/reservations" => "reservations#index", as: 'reservations'
#get "/reservations/new" => "reservations#new", as: 'new_reservation'
#get "/reservations/:id" => "reservations#show", as: 'reservation'
#post "/reservations" => "reservations#create"
#get "/reservations/:id/edit" => "reservations#edit", as: 'edit_reservation'
#patch "/reservations/:id" => "reservations#update"
#delete "/reservations/:id" => "reservations#destroy"

get "/overdue" => "reservations#overdue", as: 'overdue'




resources :authors

root 'books#index'

end

app/views/layouts/_footer.html.erb
<%- if user_signed_in? %>
<nav class="navbar navbar-default">
  <div class="container">
    <h3 class="text-center text-muted">For assistance email team7@gmail.com</h3>

    <h3 class="text-center text-muted">

    </h3>

  </div>
</nav>
<% end -%>

app/views/layouts/_header.html.erb
<header class="page-header">
<h1><%= link_to('GMU Library Project', root_path) %></h1>
</header>

app/views/layouts/_search_results.html.erb
<ul>
    <% @grants.each do |grant| %>
  <li><%= link_to grant.title, 
    :action => 'show', :id => grant.id  %></li>
  <% end %>
  </ul>

app/views/layouts/_sidebar.html.erb
<%- if user_signed_in? %>
<div id="sidebar">
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Navigation</h3>
  </div>
  <div class="panel-body">
    <p>
      <%= link_to 'All Books', books_path %>
    </p>
    <p>
      <%= link_to 'All Authors', authors_path %>
    </p>
<%- if current_user.try(:admin?)%>
    <p>
      <%= link_to 'New Book', new_book_path %>
    </p>
    <p> <%= link_to 'New Author', new_author_path %> </p>
    <p><%= link_to 'OverDue Books', overdue_path %></p>
    <p><%= link_to 'User Managment', users_path %></p>
    <p><%= link_to 'All Reservations', reservations_path %></p>
<% end -%>
<%- if !current_user.try(:admin?)%>
    <p><%= link_to 'My Reservations', reservations_path %></p>
<% end -%>
    <p>
    <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
    </p>
  </div>
</div>
</div>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Library</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
    <%= render '/layouts/header' %>
  </div>
  <div class="container">
     <% if !current_user.nil?%>
     <div align="right" id="search">
      <%= render :partial => 'books/search' %>
     </div>
      <% end %>
    <div class="col-xs-9">
      <%= render '/shared/flashes' %>
      <%= yield %>
    </div>
    <div class="col-xs-3">
      <%= render '/layouts/sidebar' %>
    </div>
  </div>
  <%= render '/layouts/footer' %>

</body>
</html>